config/routes.rb
Rails.application.routes.draw do
  get 'sellers' => 'sellers#index' 
  get 'sellers/:id/items_sold' => 'sellers#items_sold' 

  get 'categories' => 'categories#index'
  get 'categories/:id/items_available' => 'categories#items_available' 

  get 'items' => 'items#index' 
  get 'items/:id' => 'items#show'

end

app/models/category.rb
class Category < ActiveRecord::Base

  has_many :items

  #attr_accessor :name

  # results per page for paginate gem
  self.per_page = 20
end

app/models/item.rb
class Item < ActiveRecord::Base

  belongs_to :category
  belongs_to :seller

  scope :available, -> { where(status: AVAILABLE_STATE) }
  scope :sold, -> { where(status: 'sold') }
  # attr_accessor :category_id, :category, :seller_id, :seller, :title, :description, 
  #               :price_in_cents, :status, :published_date

  AVAILABLE_STATE = ["available", "pending"]
  UNAVAILABLE_STATE = ["sold", "expired", "banned"]
  STATES = AVAILABLE_STATE + UNAVAILABLE_STATE

  validates :category, presence: true, allow_nil: false
  validates :seller, presence: true, allow_nil: false
  # You may want to add unique validation on title and seller to prevent
  # a seller having multiple listings with the same name to avoid confusion
  validates :title, presence: true, allow_nil: false
  validates :description, presence: true, allow_nil: false
  validates :price_in_cents, presence: true, allow_nil: false
  validate :valid_status

  before_create :set_defaults

  def set_defaults
    self.published_date = Time.now.utc
  end

  def valid_status
    unless STATES.include?(self.status)
      @errors[:status] << "Status must be #{STATES}"
    end
  end

  def banned?
    status == 'banned'
  end

  # results per page for paginate gem
  self.per_page = 20
end

app/models/seller.rb
class Seller < ActiveRecord::Base

  has_many :items

  #attr_accessor :name, :latitude, :longitude

  # results per page for paginate gem
  self.per_page = 20
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  around_action :rescue_exceptions

  def rescue_exceptions
    yield
  rescue => e
    render message: "Error #{e.class.name} #{e.message}", status: 400
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:items_available]

  # GET /categories.json
  def index
    @categories = Category.paginate(:page => params[:page])
    respond_to do |format|
      format.json { render json: @categories, status: 200}
    end
  end

  # GET /categories/:id/items_available.json&page=1
  def items_available
    @items = @category.items.available.paginate(:page => params[:page])
    respond_to do |format|
      format.json { render json: @items, status: 200}
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show]

  # GET /items
  # GET /items.json
  def index
    @items = Item.paginate(:page => params[:page])
    respond_to do |format|
      format.json { render json: @items, status: 200}
    end
  end

  # GET /items/1
  # GET /items/1.json
  def show
    respond_to do |format|
      format.json { render json: @item, status: 200}
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end
end

app/controllers/sellers_controller.rb
class SellersController < ApplicationController
  before_action :set_seller, only: [:items_sold]

  # GET /sellers.json&page=1
  def index
    @sellers = Seller.paginate(:page => params[:page])
    respond_to do |format|
      format.json { render json: @sellers, status: 200}
    end
  end

  # GET /sellers/:id/items_sold.json&page=1
  def items_sold
    @items = @seller.items.sold.paginate(:page => params[:page])
    respond_to do |format|
      format.json { render json: @items, status: 200}
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_seller
      @seller = Seller.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def seller_params
      params.require(:seller).permit(:name, :latitude, :longitude)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/sellers_helper.rb
module SellersHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :category_id %><br>
    <%= f.number_field :category_id %>
  </div>
  <div class="field">
    <%= f.label :seller_id %><br>
    <%= f.number_field :seller_id %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :price_in_cents %><br>
    <%= f.number_field :price_in_cents %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.text_field :status %>
  </div>
  <div class="field">
    <%= f.label :published_date %><br>
    <%= f.date_select :published_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Items</h1>

<table>
  <thead>
    <tr>
      <th>Category</th>
      <th>Seller</th>
      <th>Description</th>
      <th>Price in cents</th>
      <th>Status</th>
      <th>Published date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.category_id %></td>
        <td><%= item.seller_id %></td>
        <td><%= item.description %></td>
        <td><%= item.price_in_cents %></td>
        <td><%= item.status %></td>
        <td><%= item.published_date %></td>
        <td><%= link_to 'Show', item %></td>
        <td><%= link_to 'Edit', edit_item_path(item) %></td>
        <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item', new_item_path %>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Category:</strong>
  <%= @item.category_id %>
</p>

<p>
  <strong>Seller:</strong>
  <%= @item.seller_id %>
</p>

<p>
  <strong>Description:</strong>
  <%= @item.description %>
</p>

<p>
  <strong>Price in cents:</strong>
  <%= @item.price_in_cents %>
</p>

<p>
  <strong>Status:</strong>
  <%= @item.status %>
</p>

<p>
  <strong>Published date:</strong>
  <%= @item.published_date %>
</p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>VarageSale</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/sellers/_form.html.erb
<%= form_for(@seller) do |f| %>
  <% if @seller.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@seller.errors.count, "error") %> prohibited this seller from being saved:</h2>

      <ul>
      <% @seller.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sellers/edit.html.erb
<h1>Editing Seller</h1>

<%= render 'form' %>

<%= link_to 'Show', @seller %> |
<%= link_to 'Back', sellers_path %>

app/views/sellers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Sellers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sellers.each do |seller| %>
      <tr>
        <td><%= seller.name %></td>
        <td><%= seller.latitude %></td>
        <td><%= seller.longitude %></td>
        <td><%= link_to 'Show', seller %></td>
        <td><%= link_to 'Edit', edit_seller_path(seller) %></td>
        <td><%= link_to 'Destroy', seller, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Seller', new_seller_path %>

app/views/sellers/new.html.erb
<h1>New Seller</h1>

<%= render 'form' %>

<%= link_to 'Back', sellers_path %>

app/views/sellers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @seller.name %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @seller.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @seller.longitude %>
</p>

<%= link_to 'Edit', edit_seller_path(@seller) %> |
<%= link_to 'Back', sellers_path %>